{
	"CT":"当前水温",
	"ST":"设置水温",
	"LT":"剩余运行时间",
	"HOUR":"小时",
	"MINIUTE":"分钟",
	"ERR_0":"无故障",
	"ERR_1":"! 水泵或电磁阀故障",
	"ERR_2":"! 温度传感器A故障",
	"ERR_3":"! 水位低",
	"ERR_4":"! 温度传感器B故障",
	"ERR_5":"! 加热管自动保护",
	"ERR_6":"! WiFi不匹配",
	"ERR_7":"! 设备离线",
	"ERR_CON":"连接未成功，请重试...",
	"FT":"定时",
	"FM":"防冻",
	"ES":"优睡",
	"SM":"睡眠",
	"CONFIRM":"确认",
	"CANCEL":"取消",
	"TIME":"时间",
	"TEMP":"温度",
	"TIMEOFF":"定时关机",
	"SETPSW":"输入设备密码",
	"AFTER":"后",
	"DEL_FOR_OWNER":"已被主人删除",
	"CON_LOSS":"连接丢失，请重新连接...",
	"PSW_NONULL":"密码不能为空",
	"PSW_ERR":"密码错误",
	"INPUT_FAIL":"输入失败3次，将回到列表页面",
	"OK_SEND":"按'确定'发送",



	"DEVICE_DN":"设备配网",
	"EDITNAME":"修改名称",
	"ALLOW":"允许控制",
	"state_0":"离线",
	"state_1":"在线",
	"DELETE":"删除",
	"ENAME":"改名",
	"JN":"权限",
	"SHARE":"分享",
	"BIND_DEVICE":"请扫设备二维码进行绑定,",
	"GOTOWEB":"或到泰和美官网逛逛",
	"WRITE":"写点什么吧",
	"MORE":"超过字数咯",
	"ENAME_FAIL":"修改名称失败",
	"DEL_DEVICE":"真的要移除设备吗？",
	"DEL_DEVICE_SUCCESS":"移除设备成功",
	"DEL_DEVICE_FAIL":"移除设备失败",
	"ALREADY_SHARE":"已被分享，快来点击"
}